In [3]:
# This is a note

import pandas as pd 

# Load the CSV file into a DataFrame
df = pd.read_csv("rawdata\RawData.csv")
df.columns = [col[:30] + '...' if len(col) > 30 else col for col in df.columns]  

# 1. View the first 5 rows
df.head()

,Informed Consent,School ( Please. Dont Abbrevi...,College/Department ( Please. D...,Program (Please. Dont Abbrev...,Age,Current Year Level,What language or dialect are y...,"Academic Stress (e.g., heavy w...",Personal / Intrapersonal Stres...,Interpersonal / Social Stress ...,...,When considering using an AI f...,To encourage daily mental well...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,"For the ""Emergency Fast-Tracki...",Suggestions:\nDo you have any o...,Required to take part. Tick ea...
0,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of Information Technology and Computin...,Information Technology,22.0,Second Year,English,Monthly,Monthly,Weekly,...,"Lack of genuine human empathy, warmth, and emo...",An interactive wellness calendar to visually t...,2,2,1,3,3,I do not mind the system sharing my data with ...,prioritize traffic handling and fallback for A...,I certify that the information I provide is tr...
1,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of information technology and computing,information technology,21.0,Fourth Year,"English, Filipino/Tagalog, Cebuano/Bisaya",Weekly,Daily,Weekly,...,Data privacy and security (fear of my conversa...,"Caring for a virtual pet (e.g., orange tabbies...",4,4,4,4,4,Only if the AI explicitly asks for my permissi...,nooe,I certify that the information I provide is tr...
2,"I have read the survey cover letter, my questi...",University of Science and Technology of the Ph...,College of Engineering and Architecture,Bachelor of Science in Electrical Engineering,22.0,Fifth Year,"English, Filipino/Tagalog, Cebuano/Bisaya, Bis...",Daily,Daily,Weekly,...,"Lack of genuine human empathy, warmth, and emo...",add quality reels,3,5,3,3,3,I do not mind the system sharing my data with ...,none,I certify that the information I provide is tr...
3,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of Information Technology and Computing,Bachelor of Science in Information Technology,21.0,Third Year,English,Weekly,Daily,Rarely,...,Data privacy and security (fear of my conversa...,"Caring for a virtual pet (e.g., orange tabbies...",1,2,4,5,2,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...
4,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,Bachelor of Science of Education,Major in Mathematics,22.0,Fourth Year,"Filipino/Tagalog, Cebuano/Bisaya",Weekly,Daily,Weekly,...,Data privacy and security (fear of my conversa...,"Caring for a virtual pet (e.g., orange tabbies...",1,1,1,1,1,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...

In [4]:
df.shape

(709, 31)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 709 entries, 0 to 708
Data columns (total 31 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Informed Consent                   709 non-null    str
 1   School ( Please.  Dont Abbrevi...  707 non-null    str
 2   College/Department ( Please. D...  671 non-null    str
 3   Program   (Please. Dont Abbrev...  662 non-null    str
 4   Age                                672 non-null    float64
 5   Current Year Level                 688 non-null    str
 6   What language or dialect are y...  702 non-null    str
 7   Academic Stress (e.g., heavy w...  709 non-null    str
 8   Personal / Intrapersonal Stres...  709 non-null    str
 9   Interpersonal / Social Stress ...  709 non-null    str
 10  Environmental / Financial Stre...  709 non-null    str
 11  When you are experiencing high...  709 non-null    str
 12  When experiencing emotional di...  709 non-null    str
 13  Have you ever attempted to sch...  709 non-null    str
 14  If you answered YES, how would...  160 non-null    float64
 15  If you answered YES, what happ...  123 non-null    str
 16  If you answered NO, what is th...  646 non-null    str
 17  What time of day do you most f...  709 non-null    str
 18  Which of the following Amuma A...  704 non-null    str
 19  Amuma AI is designed for mobil...  709 non-null    str
 20  Amuma AI allows you to vent vi...  709 non-null    str
 21  When considering using an AI f...  705 non-null    str
 22  To encourage daily mental well...  703 non-null    str
 23  Rank the following factors by ...  709 non-null    int64
 24  Rank the following factors by ...  709 non-null    int64
 25  Rank the following factors by ...  709 non-null    int64
 26  Rank the following factors by ...  709 non-null    int64
 27  Rank the following factors by ...  709 non-null    int64
 28  For the "Emergency Fast-Tracki...  703 non-null    str
 29  Suggestions:
Do you have any o...  87 non-null     str
 30  Required to take part. Tick ea...  709 non-null    str
dtypes: float64(2), int64(5), str(24)
memory usage: 171.8 KB

In [11]:
# View the rows where the School column is missing (null)
empty_school_rows = df[df["School ( Please.  Dont Abbreviate)"].isnull()]

# Display the result
empty_school_rows

,Informed Consent,School ( Please. Dont Abbreviate),College/Department ( Please. Dont Abbreviate),Program (Please. Dont Abbreviate),Age,Current Year Level,What language or dialect are you most comfortable using when expressing complex emotions or mental health struggles? \n\n,"Academic Stress (e.g., heavy workload, difficulty of subjects, upcoming exams, deadlines) [Choose]","Personal / Intrapersonal Stress (e.g., changes in sleeping or eating habits, personal health, taking on new responsibilities) \n [Choose]","Interpersonal / Social Stress (e.g., peer relationships, romantic issues, conflicts with friends or family) [Choose]",...,"When considering using an AI for mental health support, what is your primary concern or reason for distrust? (Checkbox, multi-select)","To encourage daily mental wellness, Amuma AI includes gamified features. Which of these would motivate you most to open the app every day? (Checkbox, multi-select)","Rank the following factors by priority when using a digital mental health platform. (1 = Most Important, 5 = Least Important) [Strict data privacy and anonymity]","Rank the following factors by priority when using a digital mental health platform. (1 = Most Important, 5 = Least Important) [A natural, empathetic, and non-robotic AI tone]","Rank the following factors by priority when using a digital mental health platform. (1 = Most Important, 5 = Least Important) [A frictionless, easy way to book a human professional if needed]","Rank the following factors by priority when using a digital mental health platform. (1 = Most Important, 5 = Least Important) [The ability to communicate via voice/audio instead of typing]","Rank the following factors by priority when using a digital mental health platform. (1 = Most Important, 5 = Least Important) [Gamified post-counseling support and daily wellness tracking (e.g., virtual pets and streaks)]","For the ""Emergency Fast-Tracking"" feature to work during a severe crisis, the system may need to securely bridge your anonymous profile to campus or city health services. Under what condition would you accept this? (Multiple choice)","Suggestions:\nDo you have any other suggestions, privacy concerns, or specific features you would want to see in a university mental health application? (Open-ended, optional)",Required to take part. Tick each box:
55,"I have read the survey cover letter, my questi...",NaN,NaN,NaN,21.0,TESDA,Cebuano/Bisaya,Never,Never,Never,...,NaN,NaN,1,1,1,1,1,NaN,NaN,I certify that the information I provide is tr...
59,"I have read the survey cover letter, my questi...",NaN,NaN,NaN,23.0,NaN,Cebuano/Bisaya,Never,Daily,Weekly,...,Data privacy and security (fear of my conversa...,None of these / Gamification would not motivat...,1,3,2,2,3,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...

In [25]:
# Grab the exact, perfectly spelled column name directly from the data 
school_col_name = df.columns[1] 
 # Set it to "Not in School" where it is null
df.loc[df[school_col_name].isnull(), school_col_name] = "Not in School" 

# Check if there are any nulls left 
df[school_col_name].isnull().sum()

 # Display rows 55 and 59 
df.iloc[[55, 59]]

,Informed Consent,School ( Please. Dont Abbrevi...,College/Department ( Please. D...,Program (Please. Dont Abbrev...,Age,Current Year Level,What language or dialect are y...,"Academic Stress (e.g., heavy w...",Personal / Intrapersonal Stres...,Interpersonal / Social Stress ...,...,When considering using an AI f...,To encourage daily mental well...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,"For the ""Emergency Fast-Tracki...",Suggestions:\nDo you have any o...,Required to take part. Tick ea...
55,"I have read the survey cover letter, my questi...",Not in School,NaN,NaN,21.0,TESDA,Cebuano/Bisaya,Never,Never,Never,...,NaN,NaN,1,1,1,1,1,NaN,NaN,I certify that the information I provide is tr...
59,"I have read the survey cover letter, my questi...",Not in School,NaN,NaN,23.0,NaN,Cebuano/Bisaya,Never,Daily,Weekly,...,Data privacy and security (fear of my conversa...,None of these / Gamification would not motivat...,1,3,2,2,3,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...

In [ ]:
# Grab the exact, perfectly spelled column name directly from the data 
school_col_name = df.columns[1] 
 # Set it to "Not in School" where it is null
df.loc[df[school_col_name].isnull(), school_col_name] = "Not in School" 

# Check if there are any nulls left 
df[school_col_name].isnull().sum()

 # Display rows 55 and 59 
df.iloc[[55, 59]]

,Informed Consent,School ( Please. Dont Abbrevi...,College/Department ( Please. D...,Program (Please. Dont Abbrev...,Age,Current Year Level,What language or dialect are y...,"Academic Stress (e.g., heavy w...",Personal / Intrapersonal Stres...,Interpersonal / Social Stress ...,...,When considering using an AI f...,To encourage daily mental well...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,"For the ""Emergency Fast-Tracki...",Suggestions:\nDo you have any o...,Required to take part. Tick ea...
55,"I have read the survey cover letter, my questi...",Not in School,NaN,NaN,21.0,TESDA,Cebuano/Bisaya,Never,Never,Never,...,NaN,NaN,1,1,1,1,1,NaN,NaN,I certify that the information I provide is tr...
59,"I have read the survey cover letter, my questi...",Not in School,NaN,NaN,23.0,NaN,Cebuano/Bisaya,Never,Daily,Weekly,...,Data privacy and security (fear of my conversa...,None of these / Gamification would not motivat...,1,3,2,2,3,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...

In [28]:
# The exact name of your School column (using the trick from earlier to prevent KeyErrors) 
school_col_name = df.columns[1]  

# The columns you want to change
columns_to_update = [
    "College/Department ( Please. Dont Abbreviate)",
    "Program   (Please. Dont Abbreviate)",
    "Current Year Level"
]


columns_to_update = [df.columns[2], df.columns[3], df.columns[5]]
df.loc[df[df.columns[1]] == "Not in School", columns_to_update] = "Not in School" 


df.iloc[[55, 59]]

,Informed Consent,School ( Please. Dont Abbrevi...,College/Department ( Please. D...,Program (Please. Dont Abbrev...,Age,Current Year Level,What language or dialect are y...,"Academic Stress (e.g., heavy w...",Personal / Intrapersonal Stres...,Interpersonal / Social Stress ...,...,When considering using an AI f...,To encourage daily mental well...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,"For the ""Emergency Fast-Tracki...",Suggestions:\nDo you have any o...,Required to take part. Tick ea...
55,"I have read the survey cover letter, my questi...",Not in School,Not in School,Not in School,21.0,Not in School,Cebuano/Bisaya,Never,Never,Never,...,NaN,NaN,1,1,1,1,1,NaN,NaN,I certify that the information I provide is tr...
59,"I have read the survey cover letter, my questi...",Not in School,Not in School,Not in School,23.0,Not in School,Cebuano/Bisaya,Never,Daily,Weekly,...,Data privacy and security (fear of my conversa...,None of these / Gamification would not motivat...,1,3,2,2,3,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 709 entries, 0 to 708
Data columns (total 31 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Informed Consent                   709 non-null    str
 1   School ( Please.  Dont Abbrevi...  707 non-null    str
 2   College/Department ( Please. D...  671 non-null    str
 3   Program   (Please. Dont Abbrev...  662 non-null    str
 4   Age                                709 non-null    float64
 5   Current Year Level                 709 non-null    str
 6   What language or dialect are y...  702 non-null    str
 7   Academic Stress (e.g., heavy w...  709 non-null    str
 8   Personal / Intrapersonal Stres...  709 non-null    str
 9   Interpersonal / Social Stress ...  709 non-null    str
 10  Environmental / Financial Stre...  709 non-null    str
 11  When you are experiencing high...  709 non-null    str
 12  When experiencing emotional di...  709 non-null    str
 13  Have you ever attempted to sch...  709 non-null    str
 14  If you answered YES, how would...  160 non-null    float64
 15  If you answered YES, what happ...  123 non-null    str
 16  If you answered NO, what is th...  646 non-null    str
 17  What time of day do you most f...  709 non-null    str
 18  Which of the following Amuma A...  704 non-null    str
 19  Amuma AI is designed for mobil...  709 non-null    str
 20  Amuma AI allows you to vent vi...  709 non-null    str
 21  When considering using an AI f...  705 non-null    str
 22  To encourage daily mental well...  703 non-null    str
 23  Rank the following factors by ...  709 non-null    int64
 24  Rank the following factors by ...  709 non-null    int64
 25  Rank the following factors by ...  709 non-null    int64
 26  Rank the following factors by ...  709 non-null    int64
 27  Rank the following factors by ...  709 non-null    int64
 28  For the "Emergency Fast-Tracki...  703 non-null    str
 29  Suggestions:
Do you have any o...  87 non-null     str
 30  Required to take part. Tick ea...  709 non-null    str
dtypes: float64(2), int64(5), str(24)
memory usage: 171.8 KB

In [11]:
 # Count the number of nulls in column index 5 (Current Year Level)
null_count = df[df.columns[5]].isnull().sum()
print(f"Number of missing values: {null_count}")

Number of missing values: 0

In [10]:
# Grab the exact name of column index 5 (Current Year Level)
year_col_name = df.columns[5]

# Fill all the null (empty) values with "Second Year"
df[year_col_name] = df[year_col_name].fillna("Second Year")

# Optional: Run this to verify the count of nulls is now 0!

df[year_col_name].isnull().sum()

np.int64(0)

In [9]:
# Grab exact column names to prevent KeyErrors
age_col = df.columns[4]
year_col = df.columns[5]

# 1st Year = 19
df.loc[
    df[age_col].isnull() &
    df[year_col].str.contains("1st|First", case=False, na=False),
    age_col
] = 19

# 2nd Year = 20
df.loc[
    df[age_col].isnull() &
    df[year_col].str.contains("2nd|Second", case=False, na=False),
    age_col
] = 20

# 3rd Year = 21
df.loc[
    df[age_col].isnull() &
    df[year_col].str.contains("3rd|Third", case=False, na=False),
    age_col
] = 21

# 4th Year = 22
df.loc[
    df[age_col].isnull() &
    df[year_col].str.contains("4th|Fourth", case=False, na=False),
    age_col
] = 22

# 5th Year = 23
df.loc[
df[age_col].isnull() &
df[year_col].str.contains("5th|Fifth", case=False, na=False),
age_col
] = 23

# Optional: Verify if there are any nulls left in Age
remaining_nulls = df[age_col].isnull().sum()
print(f"Remaining null values in Age column: {remaining_nulls}")

Remaining null values in Age column: 8

In [7]:
age_col = df.columns[4] 
df[df[age_col].isnull()]

,Informed Consent,School ( Please. Dont Abbrevi...,College/Department ( Please. D...,Program (Please. Dont Abbrev...,Age,Current Year Level,What language or dialect are y...,"Academic Stress (e.g., heavy w...",Personal / Intrapersonal Stres...,Interpersonal / Social Stress ...,...,When considering using an AI f...,To encourage daily mental well...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,"For the ""Emergency Fast-Tracki...",Suggestions:\nDo you have any o...,Required to take part. Tick ea...
269,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,Second Year,"English, Filipino/Tagalog, Cebuano/Bisaya",Monthly,Rarely,Weekly,...,Fear of the AI hallucinating or giving generic...,An interactive wellness calendar to visually t...,5,4,1,3,2,I would never accept this; I want complete ano...,NaN,I certify that the information I provide is tr...
271,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,Second Year,Cebuano/Bisaya,Weekly,Daily,Never,...,Data privacy and security (fear of my conversa...,Viewing visual graphs of my mood and stress le...,5,3,4,4,5,I do not mind the system sharing my data with ...,NaN,I certify that the information I provide is tr...
272,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,Second Year,"English, Filipino/Tagalog, Cebuano/Bisaya",Daily,Daily,Daily,...,Data privacy and security (fear of my conversa...,Earning achievements for completing CBT micro-...,1,5,4,2,3,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...
285,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,NaN,"English, Cebuano/Bisaya",Weekly,Daily,Rarely,...,Data privacy and security (fear of my conversa...,"Caring for a virtual pet (e.g., orange tabbies...",1,3,2,4,5,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...
321,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of Information Technology and Computing,IT,NaN,Third Year,"English, Cebuano/Bisaya",Daily,Weekly,Rarely,...,"Lack of genuine human empathy, warmth, and emo...",None of these / Gamification would not motivat...,1,2,4,3,5,I would never accept this; I want complete ano...,NaN,I certify that the information I provide is tr...
341,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of Information Technology and Computing,IT,NaN,Third Year,Taglish,Daily,Daily,Weekly,...,Data privacy and security (fear of my conversa...,Building a daily streak for checking in.,4,4,4,4,1,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...
373,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of Engineering and Architecture,BSCE,NaN,First Year,English,Weekly,Rarely,Rarely,...,Data privacy and security (fear of my conversa...,"Building a daily streak for checking in., Earn...",1,3,4,2,5,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...
377,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,Second Year,Cebuano/Bisaya,Rarely,Rarely,Never,...,"Lack of genuine human empathy, warmth, and emo...",Viewing visual graphs of my mood and stress le...,5,5,1,1,1,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...
379,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,First Year,"English, Filipino/Tagalog, Cebuano/Bisaya, Tag...",Rarely,Rarely,Rarely,...,Data privacy and security (fear of my conversa...,An interactive wellness calendar to visually t...,1,2,3,5,4,I do not mind the system sharing my data with ...,NaN,I certify that the information I provide is tr...
388,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of Science and Technology Education,SCI ED,NaN,NaN,Cebuano/Bisaya,Daily,Daily,Rarely,...,"Lack of genuine human empathy, warmth, and emo...",An interactive wellness calendar to visually t...,1,1,5,1,1,I do not mind the system sharing my data with ...,NaN,I certify that the information I provide is tr...
395,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,First Year,English,Daily,Daily,Daily,...,Data privacy and security (fear of my conversa...,Viewing visual graphs of my mood and stress le...,1,2,3,5,4,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...
396,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,First Year,Cebuano/Bisaya,Weekly,Weekly,Weekly,...,Data privacy and security (fear of my conversa...,Viewing visual graphs of my mood and stress le...,1,5,4,2,1,I do not mind the system sharing my data with ...,NaN,I certify that the information I provide is tr...
435,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,NaN,Cebuano/Bisaya,Weekly,Monthly,Rarely,...,Data privacy and security (fear of my conversa...,None of these / Gamification would not motivat...,1,4,2,3,5,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...
442,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,BSED,NaN,First Year,"English, Filipino/Tagalog",Weekly,Weekly,Weekly,...,NaN,Building a daily streak for checking in.,1,1,1,1,1,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...
452,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,Second Year,Taglish,Daily,Weekly,Daily,...,"Lack of genuine human empathy, warmth, and emo...",Earning achievements for completing CBT micro-...,1,2,1,1,1,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...
460,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of Science and Technology Education,NaN,NaN,Third Year,English,Daily,Daily,Rarely,...,Data privacy and security (fear of my conversa...,Earning achievements for completing CBT micro-...,1,2,3,4,5,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...
461,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,Fourth Year,Taglish,Daily,Daily,Weekly,...,Data privacy and security (fear of my conversa...,Earning achievements for completing CBT micro-...,1,1,2,3,4,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...
467,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,Third Year,"Filipino/Tagalog, Cebuano/Bisaya",Daily,Daily,Rarely,...,Data privacy and security (fear of my conversa...,"Caring for a virtual pet (e.g., orange tabbies...",1,1,1,1,1,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...
473,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,First Year,Cebuano/Bisaya,Weekly,Rarely,Never,...,"Lack of genuine human empathy, warmth, and emo...",An interactive wellness calendar to visually t...,1,5,1,1,1,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...
484,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,First Year,"English, Filipino/Tagalog, Cebuano/Bisaya, Bis...",Daily,Daily,Daily,...,Data privacy and security (fear of my conversa...,An interactive wellness calendar to visually t...,5,1,1,1,1,I would never accept this; I want complete ano...,NaN,I certify that the information I provide is tr...
516,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of Science and Technology Education,BTLED,NaN,NaN,"Filipino/Tagalog, Cebuano/Bisaya",Daily,Daily,Daily,...,"Lack of genuine human empathy, warmth, and emo...","Caring for a virtual pet (e.g., orange tabbies...",3,2,1,2,2,I do not mind the system sharing my data with ...,NaN,I certify that the information I provide is tr...
522,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,First Year,"English, Cebuano/Bisaya",Never,Daily,Never,...,"Lack of genuine human empathy, warmth, and emo...",Earning achievements for completing CBT micro-...,2,1,5,3,4,I would never accept this; I want complete ano...,NaN,I certify that the information I provide is tr...
533,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of Information Technology and Computing,IT,NaN,Second Year,Taglish,Daily,Daily,Never,...,Data privacy and security (fear of my conversa...,Earning achievements for completing CBT micro-...,1,3,2,4,5,I do not mind the system sharing my data with ...,NaN,I certify that the information I provide is tr...
556,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,NaN,Filipino/Tagalog,Rarely,Weekly,Daily,...,"Lack of genuine human empathy, warmth, and emo...",Earning achievements for completing CBT micro-...,5,5,5,5,5,I would never accept this; I want complete ano...,NaN,I certify that the information I provide is tr...
559,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,Second Year,Filipino/Tagalog,Weekly,Daily,Daily,...,"Lack of genuine human empathy, warmth, and emo...",Earning achievements for completing CBT micro-...,1,1,1,1,1,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...
567,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,First Year,Filipino/Tagalog,Daily,Weekly,Monthly,...,Data privacy and security (fear of my conversa...,"Caring for a virtual pet (e.g., orange tabbies...",4,3,5,2,1,I do not mind the system sharing my data with ...,NaN,I certify that the information I provide is tr...
569,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,First Year,"Filipino/Tagalog, Cebuano/Bisaya, Taglish",Weekly,Daily,Weekly,...,"Lack of genuine human empathy, warmth, and emo...","Caring for a virtual pet (e.g., orange tabbies...",1,1,1,1,1,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...
579,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of Information Technology and Computing,TCM,NaN,First Year,"English, Cebuano/Bisaya, Taglish",Daily,Daily,Rarely,...,"Lack of genuine human empathy, warmth, and emo...","Caring for a virtual pet (e.g., orange tabbies...",1,2,4,5,3,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...
610,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,Fifth Year,English,Rarely,Never,Never,...,"Lack of genuine human empathy, warmth, and emo...","Caring for a virtual pet (e.g., orange tabbies...",1,2,4,3,3,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...
615,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,TCM,NaN,Third Year,NaN,Daily,Daily,Daily,...,Data privacy and security (fear of my conversa...,None of these / Gamification would not motivat...,1,2,4,3,5,Only if the AI explicitly asks for my permissi...,NaN,I certify that the information I provide is tr...
624,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,First Year,Cebuano/Bisaya,Daily,Daily,Weekly,...,Data privacy and security (fear of my conversa...,"Caring for a virtual pet (e.g., orange tabbies...",1,2,4,3,5,I would never accept this; I want complete ano...,NaN,I certify that the information I provide is tr...
676,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,NaN,"Cebuano/Bisaya, Taglish",Rarely,Daily,Rarely,...,"Lack of genuine human empathy, warmth, and emo...",None of these / Gamification would not motivat...,5,5,5,5,5,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...
689,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of Information Technology and Computing,IT,NaN,NaN,Filipino/Tagalog,Daily,Rarely,Daily,...,Data privacy and security (fear of my conversa...,"Caring for a virtual pet (e.g., orange tabbies...",1,5,1,5,1,I would never accept this; I want complete ano...,NaN,I certify that the information I provide is tr...
702,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,NaN,English,Rarely,Rarely,Rarely,...,"Lack of genuine human empathy, warmth, and emo...","Caring for a virtual pet (e.g., orange tabbies...",1,1,5,5,5,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...
705,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,First Year,"English, Taglish",Daily,Monthly,Rarely,...,Data privacy and security (fear of my conversa...,"Caring for a virtual pet (e.g., orange tabbies...",1,3,5,4,2,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...
706,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,First Year,Filipino/Tagalog,Daily,Daily,Rarely,...,Data privacy and security (fear of my conversa...,None of these / Gamification would not motivat...,1,5,5,1,1,I would never accept this; I want complete ano...,NaN,I certify that the information I provide is tr...
707,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,First Year,Cebuano/Bisaya,Monthly,Monthly,Rarely,...,I do not have any concerns; I fully trust AI f...,Viewing visual graphs of my mood and stress le...,1,5,1,1,1,I would never accept this; I want complete ano...,NaN,I certify that the information I provide is tr...

In [12]:
# Grab the exact name of the 5th column (Index 4, which is Age) 
age_col_name = df.columns[4]

# Display all rows where Age is missing / NaN
missing_age_rows = df[df[age_col_name].isna()] 
missing_age_rows

,Informed Consent,School ( Please. Dont Abbrevi...,College/Department ( Please. D...,Program (Please. Dont Abbrev...,Age,Current Year Level,What language or dialect are y...,"Academic Stress (e.g., heavy w...",Personal / Intrapersonal Stres...,Interpersonal / Social Stress ...,...,When considering using an AI f...,To encourage daily mental well...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,Rank the following factors by ...,"For the ""Emergency Fast-Tracki...",Suggestions:\nDo you have any o...,Required to take part. Tick ea...
285,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,Second Year,"English, Cebuano/Bisaya",Weekly,Daily,Rarely,...,Data privacy and security (fear of my conversa...,"Caring for a virtual pet (e.g., orange tabbies...",1,3,2,4,5,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...
388,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of Science and Technology Education,SCI ED,NaN,Second Year,Cebuano/Bisaya,Daily,Daily,Rarely,...,"Lack of genuine human empathy, warmth, and emo...",An interactive wellness calendar to visually t...,1,1,5,1,1,I do not mind the system sharing my data with ...,NaN,I certify that the information I provide is tr...
435,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,Second Year,Cebuano/Bisaya,Weekly,Monthly,Rarely,...,Data privacy and security (fear of my conversa...,None of these / Gamification would not motivat...,1,4,2,3,5,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...
516,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of Science and Technology Education,BTLED,NaN,Second Year,"Filipino/Tagalog, Cebuano/Bisaya",Daily,Daily,Daily,...,"Lack of genuine human empathy, warmth, and emo...","Caring for a virtual pet (e.g., orange tabbies...",3,2,1,2,2,I do not mind the system sharing my data with ...,NaN,I certify that the information I provide is tr...
556,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,Second Year,Filipino/Tagalog,Rarely,Weekly,Daily,...,"Lack of genuine human empathy, warmth, and emo...",Earning achievements for completing CBT micro-...,5,5,5,5,5,I would never accept this; I want complete ano...,NaN,I certify that the information I provide is tr...
676,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,Second Year,"Cebuano/Bisaya, Taglish",Rarely,Daily,Rarely,...,"Lack of genuine human empathy, warmth, and emo...",None of these / Gamification would not motivat...,5,5,5,5,5,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...
689,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,College of Information Technology and Computing,IT,NaN,Second Year,Filipino/Tagalog,Daily,Rarely,Daily,...,Data privacy and security (fear of my conversa...,"Caring for a virtual pet (e.g., orange tabbies...",1,5,1,5,1,I would never accept this; I want complete ano...,NaN,I certify that the information I provide is tr...
702,"I have read the survey cover letter, my questi...",University of Science and Technology of Southe...,NaN,NaN,NaN,Second Year,English,Rarely,Rarely,Rarely,...,"Lack of genuine human empathy, warmth, and emo...","Caring for a virtual pet (e.g., orange tabbies...",1,1,5,5,5,Only if I am flagged as an immediate danger to...,NaN,I certify that the information I provide is tr...

In [ ]:
# Define the mapping for Current Year Level to Age
year_to_age = {
    "First Year": 19,
    "Second Year": 20,
    "Third Year": 21,
    "Fourth Year": 22,
    "Forth Year": 22,  # Added to cover potential typos
    "Fifth Year": 23,
}

# Map the Current Year Level to ages and fill ONLY the null values in 'Age'
mapped_ages = df["Current Year Level"].map(year_to_age)
df["Age"] = df["Age"].fillna(mapped_ages)

# Check if there are any nulls left in Age
print("Remaining missing Age values:", df["Age"].isnull().sum())

Remaining missing Age values: 0

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 709 entries, 0 to 708
Data columns (total 31 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Informed Consent                   709 non-null    str
 1   School ( Please.  Dont Abbrevi...  707 non-null    str
 2   College/Department ( Please. D...  709 non-null    str
 3   Program   (Please. Dont Abbrev...  709 non-null    str
 4   Age                                709 non-null    float64
 5   Current Year Level                 709 non-null    str
 6   What language or dialect are y...  709 non-null    str
 7   Academic Stress (e.g., heavy w...  709 non-null    str
 8   Personal / Intrapersonal Stres...  709 non-null    str
 9   Interpersonal / Social Stress ...  709 non-null    str
 10  Environmental / Financial Stre...  709 non-null    str
 11  When you are experiencing high...  709 non-null    str
 12  When experiencing emotional di...  709 non-null    str
 13  Have you ever attempted to sch...  709 non-null    str
 14  If you answered YES, how would...  160 non-null    float64
 15  If you answered YES, what happ...  123 non-null    str
 16  If you answered NO, what is th...  646 non-null    str
 17  What time of day do you most f...  709 non-null    str
 18  Which of the following Amuma A...  704 non-null    str
 19  Amuma AI is designed for mobil...  709 non-null    str
 20  Amuma AI allows you to vent vi...  709 non-null    str
 21  When considering using an AI f...  705 non-null    str
 22  To encourage daily mental well...  703 non-null    str
 23  Rank the following factors by ...  709 non-null    int64
 24  Rank the following factors by ...  709 non-null    int64
 25  Rank the following factors by ...  709 non-null    int64
 26  Rank the following factors by ...  709 non-null    int64
 27  Rank the following factors by ...  709 non-null    int64
 28  For the "Emergency Fast-Tracki...  703 non-null    str
 29  Suggestions:
Do you have any o...  87 non-null     str
 30  Required to take part. Tick ea...  709 non-null    str
dtypes: float64(2), int64(5), str(24)
memory usage: 171.8 KB

In [23]:
import numpy as np

# 1. Safely grab the exact column names using their index (2 and 3)
col_dept = df.columns[2]
col_prog = df.columns[3]

# 2. List of text variations that basically mean "blank"
na_keywords = ['n/a', 'na', 'none', '-', '', 'not applicable', 'nan']

print("Standardizing College and Program columns...")

# 3. Loop through both columns to clean them
for col in [col_dept, col_prog]:
    # Find rows where the typed text matches our keywords (ignores uppercase/lowercase and spaces)
    text_matches = df[col].astype(str).str.lower().str.strip().isin(na_keywords)

    # Convert those weird text variations into actual Pandas Nulls (NaN)
    df.loc[text_matches, col] = np.nan

    # Now fill ALL nulls (both the original blanks and the ones we just converted) with the standard "N/A"
    df[col] = df[col].fillna("N/A")

# 4. Verify it worked (Both should now say 0 missing values!)
print(f"Missing values in College: {df[col_dept].isnull().sum()}")
print(f"Missing values in Program: {df[col_prog].isnull().sum()}")

Standardizing College and Program columns...
Missing values in College: 0
Missing values in Program: 0

In [21]:
# A list of words that usually mean "Not Applicable" or are manually typed blanks
na_keywords = ['n/a', 'na', 'none', 'nothing', '-', 'not applicable', 'no answer', '']

print("--- Scanning for 'N/A' or similar variations ---")
found_any = False

# We use enumerate to get both the column index (i) and the name (col)
for i, col in enumerate(df.columns):

    # 1. Grab the column by its exact numerical position (i) to avoid duplicate name errors
    # 2. Drop actual pandas nulls for the check
    # 3. Convert to string, make lowercase, and remove extra spaces
    text_data = df.iloc[:, i].dropna().astype(str).str.lower().str.strip()

    # Check if the text exactly matches any of our NA keywords
    matches = text_data[text_data.isin(na_keywords)]

    # If we found any matches, print the summary for this column
    if not matches.empty:
        found_any = True
        count = len(matches)
        unique_found = matches.unique()  # Shows exactly which variations were used

        # Truncate long column names for a cleaner print output
        display_col = col if len(col) < 60 else col[:57] + "..."

        # Print the column index along with the name to help you locate duplicates
        print(f"Column {i}: {display_col}")
        print(f"  - Found {count} instances.")
        print(f"  - Variations found: {list(unique_found)}\n")

if not found_any:
    print("No 'N/A' or similar variations were found in the dataset.")

--- Scanning for 'N/A' or similar variations ---
Column 21: When considering using an AI f...
  - Found 1 instances.
  - Variations found: ['nothing']

Column 28: For the "Emergency Fast-Tracki...
  - Found 1 instances.
  - Variations found: ['na']

Column 29: Suggestions:
Do you have any o...
  - Found 22 instances.
  - Variations found: ['none', 'nothing', 'n/a', 'na', '']

In [18]:
# Grab the exact column name for the language question (Column index 6)
language_col = df.columns[6]

# Fill any missing (null) values in this column with "English"
df[language_col] = df[language_col].fillna("English")

# Verify that there are no more missing values in this column
print("Remaining missing values:", df[language_col].isnull().sum())

Remaining missing values: 0

In [22]:
string_na_filter = df['Age'].astype(str).str.lower().str.strip().isin(['n/a', 'na', 'none'])

# View only those specific rows
df_age_text_na = df[string_na_filter]
df_age_text_na

Empty DataFrame
Columns: [Informed Consent, School ( Please.  Dont Abbrevi..., College/Department ( Please. D..., Program   (Please. Dont Abbrev..., Age, Current Year Level, What language or dialect are y..., Academic Stress (e.g., heavy w..., Personal / Intrapersonal Stres..., Interpersonal / Social Stress ..., Environmental / Financial Stre..., When you are experiencing high..., When experiencing emotional di..., Have you ever attempted to sch..., If you answered YES, how would..., If you answered YES, what happ..., If you answered NO, what is th..., What time of day do you most f..., Which of the following Amuma A..., Amuma AI is designed for mobil..., Amuma AI allows you to vent vi..., When considering using an AI f..., To encourage daily mental well..., Rank the following factors by ..., Rank the following factors by ..., Rank the following factors by ..., Rank the following factors by ..., Rank the following factors by ..., For the "Emergency Fast-Tracki..., Suggestions:
Do you have any o..., Required to take part. Tick ea...]
Index: []

[0 rows x 31 columns]

In [25]:
df.to_csv("rawdata\Cleaned_Data.csv", index=False)